---
- name: Create Multipass VMs for a K3S cluster
  hosts: localhost

  tasks:
  - name: Read cluster node VM configuration from file
    include_vars:
      file: vnodes.yml
      name: vnodes

  - name: Create keypair and cloud-init
    include_tasks: create-keys-and-cloudinit.yml
    
  - name: Create the cluster VMs
    include_tasks: delete-and-create-new-vm-tasks.yml
    vars:
      vmname: "{{ item.key }}"
      vmcreationparams: "{{ item.value }}"
    loop: "{{ vnodes | dict2items }}"
    